services:
  ollama:
    image: ollama/ollama
    container_name: ollama-local
    volumes:
      - ollama:/root/.ollama
      - ./init.sh:/init.sh
    ports:
      - 11434:11434
    entrypoint: ["bash", "/init.sh"]


volumes:
  ollama:
    name: ollama
