name: Build Java Projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'


    #Build first project
    - name: Build Monolith micro service
      run: |
        cd asi2-backendmarket-monolithic-student-master
        mvn clean install

    #Build second project
    - name: Build Properties micro service
      run: |
        cd cardPropertiesService
        mvn clean install -DskipTests